version: '3.8'

services:
  mysql-service:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bddbud
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  web-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/bddbud
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8089:8080"
    depends_on:
      - mysql-service
    restart: unless-stopped

volumes:
  mysql_data:
