version: '3.8'

services:
  web-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8089:8080"
    depends_on:
      - mysql-service

  mysql-service:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bddbud
    ports:
      - "3309:3306"
